### ISSUE TITLE
Enable in Input

### ISSUE THREAD

**Issue by fuJiin** [mathusiast/jquery.hotkeys#2]
This might be a really noob question, but is there a way to enable a bound key to work even when inside input?  

I looked all over for this, and found references to a disableInInput function somewhere, though I haven't been able to find how to disable that setting.  I'd prefer not to have to rebind every key to the inputs.  

Thanks for the help.

**Comment by mathusiast** [comment]
by default, it is enabled in input elements.
look at http://github.com/tzuryby/jquery.hotkeys/blob/master/test-static-07.html as an example

**Comment by tdm00** [comment]
@tzuryby I don't understand your comment.  I think what @fuJiin was asking, and I'm looking for, is how can we allow the key binding to work even when the input has focus?  For example, I want to have an input field have focus because I just typed something there, but then I want to be able to press control + alt + s to submit the form without losing focus on the input box.
